### PR TITLE
Support Fabric 1.21

### PR DESCRIPTION
**Pull request by hui1601**
I've patched the code to reflect the breaking changes in the Fabric API and to match Minecraft 1.21.

NOTE: Please test carefully as I don't have time to test that all the features work.

### CODE REVIEW

**Comment by WiIIiam278** [comment]
Thanks, but I currently just want to support 1.20.1 cuz that's the one with cobblemon and all the mods on

**Comment by EliasB-NU** [comment]
I compiled it myself and are running it on my server, works perfectly fine.

**Comment by Rozbiynk** [comment]
cant build latest commits
изображение

**Comment by hui1601** [comment]
@Rozbiynk That's a error related with the network status.
But, the master branch changes cause build other errors.

try below changes with latest commit.(I havn't tested this)
```patch
diff --git a/build.gradle b/build.gradle
index 86ac9d9..d993b38 100644
--- a/build.gradle
+++ b/build.gradle
@@ -131,7 +131,7 @@ subprojects {
     }
 
     // API publishing
-    if (['common', 'bukkit', 'fabric'].contains(project.name)) {
+    if (['common', 'fabric'].contains(project.name)) {
         java {
             withSourcesJar()
             withJavadocJar()
@@ -158,19 +158,6 @@ subprojects {
                 }
             }
 
-            if (['bukkit'].contains(project.name)) {
-                publications {
-                    mavenJavaBukkit(MavenPublication) {
-                        groupId = 'net.william278.husksync'
-                        artifactId = 'husksync-bukkit'
-                        version = "$rootProject.version"
-                        artifact shadowJar
-                        artifact sourcesJar
-                        artifact javadocJar
-                    }
-                }
-            }
-
             if (['fabric'].contains(project.name)) {
                 publications {
                     mavenJavaFabric(MavenPublication) {
diff --git a/settings.gradle b/settings.gradle
index fefb698..7d487df 100644
--- a/settings.gradle
+++ b/settings.gradle
@@ -8,7 +8,5 @@ pluginManagement {
 rootProject.name = 'HuskSync'
 include(
         'common',
-        'bukkit',
-        'paper',
         'fabric'
-)
\ No newline at end of file
+)

```

**Comment by Rozbiynk** [comment]
look like it compiled 
изображение

**Comment by La1m1e** [comment]
Locked map sync doesnt work for me. Also sends this message every time i switch servers or log off 
image

**Comment by La1m1e** [comment]
> Locked map sync doesnt work for me. Also sends this message every time i switch servers or log off image

Also it resets my coordinates in each server to ones on which i joined the first time, while inventory and other things sync

**Review by WiIIiam278 — APPROVED** [review]
Appreciate your work here!
We're now targeting Fabric 1.20.1 in a separate branch so we'll get this merged into master. I think there's a couple things todo after merging, but that can be tidied up before a release :)

**Pull request merged**
