### PR TITLE
Update Chinese (Simplified) translation

### PR DESCRIPTION
**Pull request by DJelly4K**
ZHCN translation for HuskSync 2.0
Im so happy to see now HuskSync has a backup system 😀
Thanks William for such a great plugin ❤❤❤

### CODE REVIEW

**Comment by WiIIiam278** [comment]
Thank you very much for your work here! However, I still have not finalized HuskSync v2.0's English locales just yet, so you'll have to redo some work I'm afraid. I will inform you when they have been frozen in place.

**Review by WiIIiam278 — CHANGES_REQUESTED** [review]
Thank you for your patience. The finalized locales to translate are available here:
https://github.com/WiIIiam278/HuskSync/blob/6bfbeec74dab9037fed2bc46ff9d153f90558c33/common/src/main/resources/locales/en-gb.yml
Please update the locales to the new english locales and this can be merged. Thanks for your work making the plugin more accessible to international users.

**Comment by DJelly4K** [comment]
> 



> Thank you for your patience. The finalized locales to translate are available here: https://github.com/WiIIiam278/HuskSync/blob/6bfbeec74dab9037fed2bc46ff9d153f90558c33/common/src/main/resources/locales/en-gb.yml Please update the locales to the new english locales and this can be merged. Thanks for your work making the plugin more accessible to international users.

Changes completed, looking forward to HuskSync 2.0 coming soon 🙂 ~~_(And HuskHomes 3.0)_~~

**Review by WiIIiam278 — APPROVED** [review]
Thank you!

**Pull request closed without merging**
